metaphlan_wc: '{fs_prefix}/{df}/taxa/mp3__{preset}__{version}/{database}/{df_sample}/{preproc}/{df_sample}.rel_ab.tsv'


mp2_out:      '{fs_prefix}/{df}/taxa/mp2__{preset}__{version}/{database}/{df_sample}/{preproc}/{df_sample}.mp2'
mp2_aligment: '{fs_prefix}/{df}/taxa/mp2__{preset}__{version}/{database}/{df_sample}/{preproc}/{df_sample}.b2'
mp2_log:      '{fs_prefix}/{df}/taxa/mp2__{preset}__{version}/{database}/{df_sample}/{preproc}/log.txt'
mp2_time:     '{fs_prefix}/{df}/taxa/mp2__{preset}__{version}/{database}/{df_sample}/{preproc}/time.txt'